spring.application.name=vehicle-maintenance-scheduler
server.port=8081
server.servlet.context-path=/

# Logging
logging.level.root=WARN
logging.level.com.scheduler=INFO

# Test Server Configuration
test.server.url=http://20.207.122.201/evaluation-service
