# Logging Middleware Configuration
test.server.url=http://20.207.122.201/evaluation-service
test.server.logs.endpoint=/logs

# Supported log levels (lowercase only)
# debug, info, warn, error, fatal

# Supported stacks
# backend, frontend

# Backend packages
# cache, controller, cron_job, db, domain, handler, repository, route, service

# Frontend packages
# api, component, hook, page, state, style

# Both stacks packages
# auth, config, middleware, utils
